create table NFF_FitnessRecord (
	uuid_ VARCHAR(75) null,
	recordId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	teacherUserId LONG,
	studentUserId LONG,
	studentGrade VARCHAR(75) null,
	studentAge INTEGER,
	testDate DATE null,
	heightFeet INTEGER,
	heightInches INTEGER,
	weight INTEGER,
	bmi INTEGER,
	triSkinfold INTEGER,
	calfSkinfold INTEGER,
	percentBodyFatCalc DOUBLE,
	percentBodyFatEntered DOUBLE,
	twentyMPacerLaps INTEGER,
	fifteenMPacerLaps INTEGER,
	pacerVo2Max DOUBLE,
	mileRunMinutes INTEGER,
	mileRunSeconds INTEGER,
	mileRunVo2Max DOUBLE,
	walkTestMinutes INTEGER,
	walkTestSeconds INTEGER,
	walkTestHrBpm INTEGER,
	walkTestVo2Max DOUBLE,
	curlUps INTEGER,
	trunkLiftInches INTEGER,
	pushups INTEGER,
	modPullUps INTEGER,
	flexArmHangSeconds INTEGER,
	sitReachLInches INTEGER,
	sitReachRInches INTEGER,
	shoulderStretchL BOOLEAN,
	shoulderStretchR BOOLEAN
);