/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package foundation.fitness.portal.service.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the FitnessRecord service. Represents a row in the &quot;NFF_FitnessRecord&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link foundation.fitness.portal.service.model.impl.FitnessRecordModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link foundation.fitness.portal.service.model.impl.FitnessRecordImpl}.
 * </p>
 *
 * @author Sten Martinez
 * @see FitnessRecord
 * @see foundation.fitness.portal.service.model.impl.FitnessRecordImpl
 * @see foundation.fitness.portal.service.model.impl.FitnessRecordModelImpl
 * @generated
 */
@ProviderType
public interface FitnessRecordModel extends BaseModel<FitnessRecord>,
	GroupedModel, ShardedModel, StagedAuditedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a fitness record model instance should use the {@link FitnessRecord} interface instead.
	 */

	/**
	 * Returns the primary key of this fitness record.
	 *
	 * @return the primary key of this fitness record
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this fitness record.
	 *
	 * @param primaryKey the primary key of this fitness record
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this fitness record.
	 *
	 * @return the uuid of this fitness record
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this fitness record.
	 *
	 * @param uuid the uuid of this fitness record
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the record ID of this fitness record.
	 *
	 * @return the record ID of this fitness record
	 */
	public long getRecordId();

	/**
	 * Sets the record ID of this fitness record.
	 *
	 * @param recordId the record ID of this fitness record
	 */
	public void setRecordId(long recordId);

	/**
	 * Returns the group ID of this fitness record.
	 *
	 * @return the group ID of this fitness record
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this fitness record.
	 *
	 * @param groupId the group ID of this fitness record
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this fitness record.
	 *
	 * @return the company ID of this fitness record
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this fitness record.
	 *
	 * @param companyId the company ID of this fitness record
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this fitness record.
	 *
	 * @return the user ID of this fitness record
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this fitness record.
	 *
	 * @param userId the user ID of this fitness record
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this fitness record.
	 *
	 * @return the user uuid of this fitness record
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this fitness record.
	 *
	 * @param userUuid the user uuid of this fitness record
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this fitness record.
	 *
	 * @return the user name of this fitness record
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this fitness record.
	 *
	 * @param userName the user name of this fitness record
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this fitness record.
	 *
	 * @return the create date of this fitness record
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this fitness record.
	 *
	 * @param createDate the create date of this fitness record
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this fitness record.
	 *
	 * @return the modified date of this fitness record
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this fitness record.
	 *
	 * @param modifiedDate the modified date of this fitness record
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the teacher user ID of this fitness record.
	 *
	 * @return the teacher user ID of this fitness record
	 */
	public long getTeacherUserId();

	/**
	 * Sets the teacher user ID of this fitness record.
	 *
	 * @param teacherUserId the teacher user ID of this fitness record
	 */
	public void setTeacherUserId(long teacherUserId);

	/**
	 * Returns the teacher user uuid of this fitness record.
	 *
	 * @return the teacher user uuid of this fitness record
	 */
	public String getTeacherUserUuid();

	/**
	 * Sets the teacher user uuid of this fitness record.
	 *
	 * @param teacherUserUuid the teacher user uuid of this fitness record
	 */
	public void setTeacherUserUuid(String teacherUserUuid);

	/**
	 * Returns the student user ID of this fitness record.
	 *
	 * @return the student user ID of this fitness record
	 */
	public long getStudentUserId();

	/**
	 * Sets the student user ID of this fitness record.
	 *
	 * @param studentUserId the student user ID of this fitness record
	 */
	public void setStudentUserId(long studentUserId);

	/**
	 * Returns the student user uuid of this fitness record.
	 *
	 * @return the student user uuid of this fitness record
	 */
	public String getStudentUserUuid();

	/**
	 * Sets the student user uuid of this fitness record.
	 *
	 * @param studentUserUuid the student user uuid of this fitness record
	 */
	public void setStudentUserUuid(String studentUserUuid);

	/**
	 * Returns the student grade of this fitness record.
	 *
	 * @return the student grade of this fitness record
	 */
	@AutoEscape
	public String getStudentGrade();

	/**
	 * Sets the student grade of this fitness record.
	 *
	 * @param studentGrade the student grade of this fitness record
	 */
	public void setStudentGrade(String studentGrade);

	/**
	 * Returns the student age of this fitness record.
	 *
	 * @return the student age of this fitness record
	 */
	public int getStudentAge();

	/**
	 * Sets the student age of this fitness record.
	 *
	 * @param studentAge the student age of this fitness record
	 */
	public void setStudentAge(int studentAge);

	/**
	 * Returns the test date of this fitness record.
	 *
	 * @return the test date of this fitness record
	 */
	public Date getTestDate();

	/**
	 * Sets the test date of this fitness record.
	 *
	 * @param testDate the test date of this fitness record
	 */
	public void setTestDate(Date testDate);

	/**
	 * Returns the height feet of this fitness record.
	 *
	 * @return the height feet of this fitness record
	 */
	public int getHeightFeet();

	/**
	 * Sets the height feet of this fitness record.
	 *
	 * @param heightFeet the height feet of this fitness record
	 */
	public void setHeightFeet(int heightFeet);

	/**
	 * Returns the height inches of this fitness record.
	 *
	 * @return the height inches of this fitness record
	 */
	public int getHeightInches();

	/**
	 * Sets the height inches of this fitness record.
	 *
	 * @param heightInches the height inches of this fitness record
	 */
	public void setHeightInches(int heightInches);

	/**
	 * Returns the weight of this fitness record.
	 *
	 * @return the weight of this fitness record
	 */
	public int getWeight();

	/**
	 * Sets the weight of this fitness record.
	 *
	 * @param weight the weight of this fitness record
	 */
	public void setWeight(int weight);

	/**
	 * Returns the bmi of this fitness record.
	 *
	 * @return the bmi of this fitness record
	 */
	public int getBmi();

	/**
	 * Sets the bmi of this fitness record.
	 *
	 * @param bmi the bmi of this fitness record
	 */
	public void setBmi(int bmi);

	/**
	 * Returns the tri skinfold of this fitness record.
	 *
	 * @return the tri skinfold of this fitness record
	 */
	public int getTriSkinfold();

	/**
	 * Sets the tri skinfold of this fitness record.
	 *
	 * @param triSkinfold the tri skinfold of this fitness record
	 */
	public void setTriSkinfold(int triSkinfold);

	/**
	 * Returns the calf skinfold of this fitness record.
	 *
	 * @return the calf skinfold of this fitness record
	 */
	public int getCalfSkinfold();

	/**
	 * Sets the calf skinfold of this fitness record.
	 *
	 * @param calfSkinfold the calf skinfold of this fitness record
	 */
	public void setCalfSkinfold(int calfSkinfold);

	/**
	 * Returns the percent body fat calc of this fitness record.
	 *
	 * @return the percent body fat calc of this fitness record
	 */
	public float getPercentBodyFatCalc();

	/**
	 * Sets the percent body fat calc of this fitness record.
	 *
	 * @param percentBodyFatCalc the percent body fat calc of this fitness record
	 */
	public void setPercentBodyFatCalc(float percentBodyFatCalc);

	/**
	 * Returns the percent body fat entered of this fitness record.
	 *
	 * @return the percent body fat entered of this fitness record
	 */
	public float getPercentBodyFatEntered();

	/**
	 * Sets the percent body fat entered of this fitness record.
	 *
	 * @param percentBodyFatEntered the percent body fat entered of this fitness record
	 */
	public void setPercentBodyFatEntered(float percentBodyFatEntered);

	/**
	 * Returns the twenty m pacer laps of this fitness record.
	 *
	 * @return the twenty m pacer laps of this fitness record
	 */
	public int getTwentyMPacerLaps();

	/**
	 * Sets the twenty m pacer laps of this fitness record.
	 *
	 * @param twentyMPacerLaps the twenty m pacer laps of this fitness record
	 */
	public void setTwentyMPacerLaps(int twentyMPacerLaps);

	/**
	 * Returns the fifteen m pacer laps of this fitness record.
	 *
	 * @return the fifteen m pacer laps of this fitness record
	 */
	public int getFifteenMPacerLaps();

	/**
	 * Sets the fifteen m pacer laps of this fitness record.
	 *
	 * @param fifteenMPacerLaps the fifteen m pacer laps of this fitness record
	 */
	public void setFifteenMPacerLaps(int fifteenMPacerLaps);

	/**
	 * Returns the pacer vo2 max of this fitness record.
	 *
	 * @return the pacer vo2 max of this fitness record
	 */
	public float getPacerVo2Max();

	/**
	 * Sets the pacer vo2 max of this fitness record.
	 *
	 * @param pacerVo2Max the pacer vo2 max of this fitness record
	 */
	public void setPacerVo2Max(float pacerVo2Max);

	/**
	 * Returns the mile run minutes of this fitness record.
	 *
	 * @return the mile run minutes of this fitness record
	 */
	public int getMileRunMinutes();

	/**
	 * Sets the mile run minutes of this fitness record.
	 *
	 * @param mileRunMinutes the mile run minutes of this fitness record
	 */
	public void setMileRunMinutes(int mileRunMinutes);

	/**
	 * Returns the mile run seconds of this fitness record.
	 *
	 * @return the mile run seconds of this fitness record
	 */
	public int getMileRunSeconds();

	/**
	 * Sets the mile run seconds of this fitness record.
	 *
	 * @param mileRunSeconds the mile run seconds of this fitness record
	 */
	public void setMileRunSeconds(int mileRunSeconds);

	/**
	 * Returns the mile run vo2 max of this fitness record.
	 *
	 * @return the mile run vo2 max of this fitness record
	 */
	public float getMileRunVo2Max();

	/**
	 * Sets the mile run vo2 max of this fitness record.
	 *
	 * @param mileRunVo2Max the mile run vo2 max of this fitness record
	 */
	public void setMileRunVo2Max(float mileRunVo2Max);

	/**
	 * Returns the walk test minutes of this fitness record.
	 *
	 * @return the walk test minutes of this fitness record
	 */
	public int getWalkTestMinutes();

	/**
	 * Sets the walk test minutes of this fitness record.
	 *
	 * @param walkTestMinutes the walk test minutes of this fitness record
	 */
	public void setWalkTestMinutes(int walkTestMinutes);

	/**
	 * Returns the walk test seconds of this fitness record.
	 *
	 * @return the walk test seconds of this fitness record
	 */
	public int getWalkTestSeconds();

	/**
	 * Sets the walk test seconds of this fitness record.
	 *
	 * @param walkTestSeconds the walk test seconds of this fitness record
	 */
	public void setWalkTestSeconds(int walkTestSeconds);

	/**
	 * Returns the walk test hr bpm of this fitness record.
	 *
	 * @return the walk test hr bpm of this fitness record
	 */
	public int getWalkTestHrBpm();

	/**
	 * Sets the walk test hr bpm of this fitness record.
	 *
	 * @param walkTestHrBpm the walk test hr bpm of this fitness record
	 */
	public void setWalkTestHrBpm(int walkTestHrBpm);

	/**
	 * Returns the walk test vo2 max of this fitness record.
	 *
	 * @return the walk test vo2 max of this fitness record
	 */
	public float getWalkTestVo2Max();

	/**
	 * Sets the walk test vo2 max of this fitness record.
	 *
	 * @param walkTestVo2Max the walk test vo2 max of this fitness record
	 */
	public void setWalkTestVo2Max(float walkTestVo2Max);

	/**
	 * Returns the curl ups of this fitness record.
	 *
	 * @return the curl ups of this fitness record
	 */
	public int getCurlUps();

	/**
	 * Sets the curl ups of this fitness record.
	 *
	 * @param curlUps the curl ups of this fitness record
	 */
	public void setCurlUps(int curlUps);

	/**
	 * Returns the trunk lift inches of this fitness record.
	 *
	 * @return the trunk lift inches of this fitness record
	 */
	public int getTrunkLiftInches();

	/**
	 * Sets the trunk lift inches of this fitness record.
	 *
	 * @param trunkLiftInches the trunk lift inches of this fitness record
	 */
	public void setTrunkLiftInches(int trunkLiftInches);

	/**
	 * Returns the pushups of this fitness record.
	 *
	 * @return the pushups of this fitness record
	 */
	public int getPushups();

	/**
	 * Sets the pushups of this fitness record.
	 *
	 * @param pushups the pushups of this fitness record
	 */
	public void setPushups(int pushups);

	/**
	 * Returns the mod pull ups of this fitness record.
	 *
	 * @return the mod pull ups of this fitness record
	 */
	public int getModPullUps();

	/**
	 * Sets the mod pull ups of this fitness record.
	 *
	 * @param modPullUps the mod pull ups of this fitness record
	 */
	public void setModPullUps(int modPullUps);

	/**
	 * Returns the flex arm hang seconds of this fitness record.
	 *
	 * @return the flex arm hang seconds of this fitness record
	 */
	public int getFlexArmHangSeconds();

	/**
	 * Sets the flex arm hang seconds of this fitness record.
	 *
	 * @param flexArmHangSeconds the flex arm hang seconds of this fitness record
	 */
	public void setFlexArmHangSeconds(int flexArmHangSeconds);

	/**
	 * Returns the sit reach l inches of this fitness record.
	 *
	 * @return the sit reach l inches of this fitness record
	 */
	public int getSitReachLInches();

	/**
	 * Sets the sit reach l inches of this fitness record.
	 *
	 * @param sitReachLInches the sit reach l inches of this fitness record
	 */
	public void setSitReachLInches(int sitReachLInches);

	/**
	 * Returns the sit reach r inches of this fitness record.
	 *
	 * @return the sit reach r inches of this fitness record
	 */
	public int getSitReachRInches();

	/**
	 * Sets the sit reach r inches of this fitness record.
	 *
	 * @param sitReachRInches the sit reach r inches of this fitness record
	 */
	public void setSitReachRInches(int sitReachRInches);

	/**
	 * Returns the shoulder stretch l of this fitness record.
	 *
	 * @return the shoulder stretch l of this fitness record
	 */
	public boolean getShoulderStretchL();

	/**
	 * Returns <code>true</code> if this fitness record is shoulder stretch l.
	 *
	 * @return <code>true</code> if this fitness record is shoulder stretch l; <code>false</code> otherwise
	 */
	public boolean isShoulderStretchL();

	/**
	 * Sets whether this fitness record is shoulder stretch l.
	 *
	 * @param shoulderStretchL the shoulder stretch l of this fitness record
	 */
	public void setShoulderStretchL(boolean shoulderStretchL);

	/**
	 * Returns the shoulder stretch r of this fitness record.
	 *
	 * @return the shoulder stretch r of this fitness record
	 */
	public boolean getShoulderStretchR();

	/**
	 * Returns <code>true</code> if this fitness record is shoulder stretch r.
	 *
	 * @return <code>true</code> if this fitness record is shoulder stretch r; <code>false</code> otherwise
	 */
	public boolean isShoulderStretchR();

	/**
	 * Sets whether this fitness record is shoulder stretch r.
	 *
	 * @param shoulderStretchR the shoulder stretch r of this fitness record
	 */
	public void setShoulderStretchR(boolean shoulderStretchR);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		foundation.fitness.portal.service.model.FitnessRecord fitnessRecord);

	@Override
	public int hashCode();

	@Override
	public CacheModel<foundation.fitness.portal.service.model.FitnessRecord> toCacheModel();

	@Override
	public foundation.fitness.portal.service.model.FitnessRecord toEscapedModel();

	@Override
	public foundation.fitness.portal.service.model.FitnessRecord toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}